Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  

### Nginx VM ###
  config.vm.define "docker" do |docker|
    docker.vm.box = "ubuntu/jammy64"
    docker.vm.hostname = "docker"
  docker.vm.network "private_network", ip: "192.168.54.11"
  docker.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1024"
   end
    docker.vm.provision "shell", path: "docker.sh"
end
  
end